version: "3.8"

services:
  client:
    build:
      context: ./Client
    ports:
      - "3000:3000"
    volumes:
      - ./Client:/app
      - /app/node_modules
    networks:
      - app-network

  server:
    build:
      context: ./Server
    ports:
      - "8001:8001"
    volumes:
      - ./Server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
