FROM node:20-alpine

WORKDIR /usr/src/app

# Add Python and other build dependencies
RUN apk add --no-cache python3 make g++ pkgconfig cairo-dev pango-dev libjpeg-turbo-dev giflib-dev

COPY package*.json ./

# Install dependencies including devDependencies
RUN npm install --include=dev

COPY . .

EXPOSE 8001

CMD ["npm", "run", "dev"]
